name: pdf_engine_vega
description: Плагин для В небо с возможностью создания, редактирования и отображения PDF файлов
version: 0.0.43
homepage: https://koldashev.ru




environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  pdfium_bindings: ^2.0.1
  path: ^1.8.2
  path_provider: ^2.1.1
  system_info2: ^4.0.0
  visibility_detector: ^0.4.0+2
  syncfusion_flutter_pdf: ^23.2.6
  #https://pub.dev/packages/pdf_text_extraction нужны библиотеки под макось андроид и иос
  pdf: ^3.10.4
  #pdfx: ^2.4.0
  pdfx:
    git:
      url: https://github.com/ScerIO/packages.flutter
      ref: 8b105a7dfc6b90220c1d79fcb805fb764cab00c5
      path: packages/pdfx


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        default_package: system_info2
      linux:
        default_package: system_info2
      macos:
        default_package: system_info2
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
